name: xcube-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7*
  #
  # runtime dependencies
  #
  - boto3
  - botocore
  - click
  - dask
  - gdal
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - pyyaml
  - s3fs
  - scipy
  - xarray
  - zarr
  #
  # development dependencies
  #
  - pytest
  - pytest-cov
  - flake8
