# Test me:
#
# xcube tile http://obs.eu-de.otc.t-systems.com/obs-esdc-v2.0.0/esdc-8d-0.083deg-1x2160x4320-2.0.0.zarr \
#   --labels time='2009-01-01/2009-12-30' \
#   --vars analysed_sst,air_temperature_2m \
#   --config config-cci-cfs.yml \
#   --style default \
#   --verbose
#
Styles:
  - Identifier: default
    ColorMappings:
      analysed_sst:
        ColorBar: "inferno"
        ValueRange: [270, 310]
      air_temperature_2m:
        ColorBar: "magma"
        ValueRange: [190, 320]
