Datasets:
  - Identifier: cyanoalert-olci-lswe-l2c-v1
    Title: "Sverige Sj\u00f6ar 2018"
    Endpoint: "http://obs.eu-de.otc.t-systems.com"
    Path: "cyanoalert/cyanoalert-olci-lswe-l2c-v1.zarr"
    FileSystem: "obs"
    Region: "eu-de"
    Style: default
    PlaceGroups:
      - PlaceGroupRef: Sweden_SE_Lakes
      - PlaceGroupRef: Sweden_SE_Bathing_Sites

PlaceGroups:
  - Identifier: Sweden_SE_Lakes
    Title: "Svenska Sj\u00f6arna"
    Path: "C:\\Users/Helge/IdeaProjects/xcube/data/places/Selected_Monitoring_Lakes_wgs84_reprojected.shp"
    CharacterEncoding: utf-8
    PropertyMapping:
      label: "SJONAMN"
      infoUrl: "URL_VISS"
  - Identifier: Sweden_SE_Bathing_Sites
    Title: "Sverige selected bathing sites"
    Path: "C:\\Users/Helge/IdeaProjects/xcube/data/places/Selected_Bathing_Sites_reprojected.shp"
    CharacterEncoding: utf-8
    PropertyMapping:
      label: "BADPLATS"
      eu_id: "EU_ID"

Styles:
  - Identifier: default
    ColorMappings:
      chl_c2rcc:
        ColorBar: "YlGn"
        ValueRange: [0., 20.]
      chl_mph:
        ColorBar: "YlGn"
        ValueRange: [0., 20.]
      iop_adg:
        ColorBar: "RdBu"
        ValueRange: [0., 2.]
      iop_agelb:
        ColorBar: "RdPu"
        ValueRange: [0., 2.]
      kd_z90max:
        ColorBar: "YlGn"
        ValueRange: [0., 1.]
      tsm_c2rcc:
        ColorBar: "viridis"
        ValueRange: [0., 100.]
      tur_nechad_665:
        ColorBar: "inferno"
        ValueRange: [0., 100.]
      tur_nechad_865:
        ColorBar: "plasma"
        ValueRange: [0., 100.]
      # min and max for the parameter below need to be adjusted! just placeholder values at the moment
      c2rcc_secchi_depth_1:
        ColorBar: "deep"
        ValueRange: [0., 20.]
      c2rcc_secchi_depth_2:
        ColorBar: "deep"
        ValueRange: [0, 20.]
      c2rcc_secchi_depth_3:
        ColorBar: "deep"
        ValueRange: [0, 20.]
      c2rcc_secchi_depth_4:
        ColorBar: "deep"
        ValueRange: [0, 20.]
      immersed_cyanobacteria:
        ColorBar: "Reds"
        ValueRange: [0, 1.]
      floating_cyanobacteria:
        ColorBar: "Blues_alpha"
        ValueRange: [0, 1.]
      floating_vegetation:
        ColorBar: "Greens_alpha"
        ValueRange: [0, 1.]
      chl_pitarch:
        ColorBar: "gnuplot"
        ValueRange: [0, 10.]

#Styles:
#  - Identifier: default
#    ColorMappings:
#      conc_chl:
#        ColorBar: "plasma"
#        ValueRange: [0., 24.]
#      conc_tsm:
#        ColorBar: "PuBuGn"
#        ValueRange: [0., 100.]
#      kd489:
#        ColorBar: "jet"
#        ValueRange: [0., 6.]

ServiceProvider:
  ProviderName: "Brockmann Consult GmbH"
  ProviderSite: "https://www.brockmann-consult.de"
  ServiceContact:
    IndividualName: "Norman Fomferra"
    PositionName: "Senior Software Engineer"
    ContactInfo:
      Phone:
        Voice: "+49 4152 889 303"
        Facsimile: "+49 4152 889 330"
      Address:
        DeliveryPoint: "HZG / GITZ"
        City: "Geesthacht"
        AdministrativeArea: "Herzogtum Lauenburg"
        PostalCode: "21502"
        Country: "Germany"
        ElectronicMailAddress: "norman.fomferra@brockmann-consult.de"

